I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/DebugDialogue.rpy", line 137, in script
    syvl "Cutting Out"
Exception: Sayer 'syvl' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/DebugDialogue.rpy", line 137, in script
    syvl "Cutting Out"
  File "C:\Program Files (x86)\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Program Files (x86)\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Program Files (x86)\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'syvl' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
TBN 1.0
Sat Feb 22 20:36:03 2025
